// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc5NdU3P86Zen7IO44OEFukZWkMwjRksE',
    appId: '1:298411862240:web:661cff8adc33e8d1984885',
    messagingSenderId: '298411862240',
    projectId: 'asynconf-767eb',
    authDomain: 'asynconf-767eb.firebaseapp.com',
    storageBucket: 'asynconf-767eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BU3ECD166uD098G5U09JhqJY3MBSd9o',
    appId: '1:298411862240:android:1cc994d0bb916e18984885',
    messagingSenderId: '298411862240',
    projectId: 'asynconf-767eb',
    storageBucket: 'asynconf-767eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsB_3GkZRDD5JEGkq8TX2Q-YuZGd3SJYQ',
    appId: '1:298411862240:ios:0233f4db3dd1854a984885',
    messagingSenderId: '298411862240',
    projectId: 'asynconf-767eb',
    storageBucket: 'asynconf-767eb.appspot.com',
    iosBundleId: 'com.example.monPremierFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsB_3GkZRDD5JEGkq8TX2Q-YuZGd3SJYQ',
    appId: '1:298411862240:ios:0233f4db3dd1854a984885',
    messagingSenderId: '298411862240',
    projectId: 'asynconf-767eb',
    storageBucket: 'asynconf-767eb.appspot.com',
    iosBundleId: 'com.example.monPremierFlutter',
  );
}
